apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nfs-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: nfs-service
  selector:
    matchLabels:
      {{- include "nfs-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nfs-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nfs-server.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
          - mountPath: /exports
            name: nfs-server-volume
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: nfs-server-volume
          persistentVolumeClaim:
            claimName: nfs-disk
      {{- end }}
